In [19]:
import numpy as np

# Generate an array by repeating a small array across each dimension
small_array = np.array([[1, 2], [3, 4]])
repeated_array = np.tile(small_array, (3, 2))

# Generate an array with element indexes such that the array elements appear in ascending order
index_array = np.arange(repeated_array.size).reshape(repeated_array.shape)

# Print the arrays
print("Small Array:")
print(small_array)

print("\nArray by Repeating Small Array:")
print(repeated_array)

print("\nArray with Element Indexes:")
print(index_array)


Small Array:
[[1 2]
 [3 4]]

Array by Repeating Small Array:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]

Array with Element Indexes:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
